version: "3.3"
services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - CLI_ARGS="–auth-mode=basic"
      - CUSTOM_PORT=8080
    volumes:
      - /volume2/Calibre/data:/config
      - /volume2/Torrents/_watch/ePub:/media/ePubs
      - /volume2/Torrents/eBooks:/media/Torrents
    ports:
      - 7080:8080
    restart: unless-stopped

  doublecommander:
    image: linuxserver/doublecommander:latest
    container_name: doublecommander
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - TITLE="DoubleCommander"
    volumes:
      - /volume1/docker/DoubleCommander/config:/config
      #- /volume1/docker/DoubleCommander/data:/data
      - /volume2/Calibre:/data/Calibre
      - /volume2/Cinema:/data/Cinema
      - /volume2/Cinema2:/data/Cinema2
      - /volume2/Cinema3:/data/Cinema3
      - /volume2/Torrents:/data/Torrents
    ports:
      - 43000:3000
    restart: unless-stopped  

#region : DOZZLE
#       : https://hub.docker.com/r/amir20/dozzle/
#__________________________________________________________________________
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - DOZZLE_NO_ANALYTICS=true
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  tmm:
    image: tinymediamanager/tinymediamanager:latest
    container_name: tmm
    environment:
      - PUID=1026
      - PGID=100
      - USER_ID=1026
      - GROUP_ID=100
      - TZ=Europe/Zurich
      - LANG=en_US.UTF-8
      - APP_NAME=TMM
      - DISPLAY=:0
      - DISPLAY_WIDTH=2560
      - DISPLAY_HEIGHT=1440
    volumes:
      - /volume2/Dockers/TMM/config:/data
      - /volume2/Dockers/TMM/addons:/app/addons
      - /volume2/Dockers/TMM/launcher-extra.yml:/app/launcher-extra.yml
      - /volume2/Cinema:/media/cinema
      - /volume2/Cinema2:/media/cinema2
      - /volume2/Cinema3:/media/cinema3
    ports:
      - 44000:4000
    restart: unless-stopped 
    
  redis:
    image: redis:alpine
    container_name: redis
    command: "redis-server --loglevel warning"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /volume1/docker/Redis/config:/usr/local/etc/redis/
      #- /volume2/Dockers/Redis/data:/data/
      - redis_data:/data/
    ports:
      - "6379:6379"
    restart: "always"

volumes:
  redis_data:
