version: "3.3"
services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - CLI_ARGS="–auth-mode=basic"
    volumes:
      - /volume2/Calibre/data:/config
    ports:
      - 7080:8080
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    command: "redis-server --loglevel warning"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /volume1/docker/Redis/config:/usr/local/etc/redis
      - /volume2/Dockers/Redis/data:/data/
      #- redis_data:/data/
    ports:
      - "6379:6379"
    restart: "always"

#  mariadb:
#    image: linuxserver/mariadb:latest
#    container_name: mariadb
#    depends_on:
#      - redis    
#    environment:
#      - PUID=1029
#      - PGID=65538
#      - TZ=Europe/Zurich
#      - MYSQL_ROOT_PASSWORD=bemr7902
#      - MYSQL_DIR=/config
#      - DATADIR=/data
#    volumes:
#      - /volume2/Dockers/MariaDB/config:/config
#      - /volume2/Dockers/MariaDB/data:/data
#    ports:
#      - 3306:3306
#    restart: unless-stopped

#  phpmyadmin:
#    image: linuxserver/phpmyadmin:latest
#    container_name: phpmyadmin
#    environment:
#      - PUID=1029
#      - PGID=65538
#      - TZ=Europe/Zurich
#      - PMA_HOST=mariadb
#      - PMA_PORT=3306
#      #- PMA_ARBITRARY=1
#    #volumes:
#    #  - /volume2/Dockers/PhpMyAdmin/config:/config
#    ports:
#      - 6180:80
#    restart: unless-stopped
    
#  adminer:
#    image: adminer:latest
#    container_name: adminer
#    depends_on:
#      - mariadb
#    environment:
#      - PUID=1029
#      - PGID=65538
#      - TZ=Europe/Zurich
#      - ADMINER_DEFAULT_SERVER=mariadb
#      - ADMINER_DEFAULT_SYSTEM=server
#      - ADMINER_DEFAULT_USERNAME=root
#      #- ADMINER_DEFAULT_PASSWORD=
#      - ADMINER_DESIGN=galkaev
#    ports:
#      - 6080:8080
#    restart: unless-stopped

#  nextcloud:
#    image: linuxserver/nextcloud:latest
#    container_name: nextcloud
#    depends_on:
#      - mariadb
#    environment:
#      - PUID=1029
#      - PGID=65538
#      - TZ=Europe/Zurich
#    volumes:
#      - /volume2/Dockers/Nextcloud/config:/config
#      - /volume2/Dockers/Nextcloud/data:/data
#    ports:
#      - 4443:443
#      - 4080:80
#    restart: unless-stopped

volumes:
  redis_data:
